import { satoshi } from "../(front)/utils/customFonts";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={satoshi.variable}>
      <body>{children}</body>
    </html>
  );
}
